<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Cruise" failures="2" tests="4" name="Test the Other" time="2.107" errors="0" timestamp="02 Oct 2021 13:05:28 GMT">
  <testcase classname="com.sk.testngsamples.OtherConcepts" name="bTest" time="0.012">
    <skipped/>
  </testcase> <!-- bTest -->
  <testcase classname="com.sk.testngsamples.OtherConcepts" name="cTest" time="2.013">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.sk.testngsamples.OtherConcepts.cTest() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.sk.testngsamples.OtherConcepts.cTest() didn't finish within the time-out 2000
at java.base@11/java.lang.invoke.MethodHandleNatives.linkMethodImpl(MethodHandleNatives.java:458)
at java.base@11/java.lang.invoke.MethodHandleNatives.linkMethod(MethodHandleNatives.java:450)
at java.base@11/java.util.concurrent.FutureTask.setException(FutureTask.java:247)
at java.base@11/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base@11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- cTest -->
  <testcase classname="com.sk.testngsamples.OtherConcepts" name="dTest" time="0.005"/>
  <testcase classname="com.sk.testngsamples.OtherConcepts" name="eTest" time="0.004">
    <failure type="org.testng.TestException" message="
Expected exception of type class java.lang.ArithmeticException but got java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.ArithmeticException but got java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
at com.sk.testngsamples.OtherConcepts.eTest(OtherConcepts.java:46)
... 19 more
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- eTest -->
  <testcase classname="com.sk.testngsamples.OtherConcepts" name="aTest" time="0.0">
    <ignored/>
  </testcase> <!-- aTest -->
</testsuite> <!-- Test the Other -->
